###
GET localhost:1111/employee

###
GET localhost:1111/employee/add?firstName=Ян&lastName=Янов

###
GET localhost:1111/employee

###
GET localhost:1111/employee/add?firstName=Ян&lastName=Янов

###
GET localhost:1111/employee/find?firstName=dfdf&lastName=dfdfdf

###
GET localhost:1111/employee/add?firstName=Ян&lastName=Янов

